---
ID: "c98294ad-5dee-45a1-8c4e-63385e6adc0c"
Parent: "a58f8d26-4aaa-4a44-b801-2463cad4ee9b"
Template: "a58f8d26-4aaa-4a44-b801-2463cad4ee9b"
Path: /sitecore/templates/Project/Main Tenant/Page Design Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {A58F8D26-4AAA-4A44-B801-2463CAD4EE9B}
    {BFAE69E1-ADD4-40A0-A593-5A793434D4F1}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200209T135754Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
