---
ID: "12f9fea8-4b34-4f46-bfb6-f2101e438be5"
Parent: "8e1ca0b8-5a9a-4353-980b-343391fe64f7"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/Main Tenant/Bysoft/Settings/Datasource Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200206T025754Z
