---
ID: "ecd8bab6-2d35-4122-9a0c-39ef3a8f7367"
Parent: "8e1ca0b8-5a9a-4353-980b-343391fe64f7"
Template: "18d0bd79-7da4-4c2a-a924-b93a2b99d669"
Path: /sitecore/content/Main Tenant/Bysoft/Settings/Shared Sites Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200206T025800Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
