---
ID: "f5ff8e51-eb3e-4e16-87d0-86bfd697533f"
Parent: "a916a6ca-82f6-4d45-ac0c-f6abbc5b100f"
Template: "a916a6ca-82f6-4d45-ac0c-f6abbc5b100f"
Path: /sitecore/templates/Project/Main Tenant/Tenant/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200208T124405Z
