---
ID: "55eeedb8-cf23-4358-b436-ddc8bd997299"
Parent: "86446286-3ba8-45c2-adbe-243d8d29c1ce"
Template: "0339bac0-78c1-43c1-b930-f8c26a5fdf80"
Path: /sitecore/content/Main Tenant/Bysoft/Presentation/Placeholder Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200206T025805Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
