---
ID: "c1ebebd7-1a28-49e4-8b4d-373ac8fc12dd"
Parent: "d877eb53-9c13-4fef-b49f-30dcedf2beb3"
Template: "2e1d7985-0bf1-469b-a00b-4f2ac443940c"
Path: /sitecore/content/Main Tenant/Global/Presentation/Rendering Variants/JSON List/Default
DB: master
BranchID: "08c12327-7685-4c17-bfca-6aae7a55f4c5"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{6E634FCA-8F4D-43E1-ADDD-5A26706605DF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200209T111322Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
