---
ID: "a69bbffc-7b01-4be9-9d76-396d1eff6779"
Parent: "b783d60b-6f2b-49c4-b1af-52e1c8d616ae"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/Main Tenant/Bysoft/Settings/Datasource Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200209T110940Z
