---
ID: "87fa8efe-96cc-4538-abc0-b038ef370801"
Parent: "8f2335ec-dccf-41af-a693-04c56ca4564e"
Template: "8f2335ec-dccf-41af-a693-04c56ca4564e"
Path: /sitecore/templates/Project/Main Tenant/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200208T124411Z
